add – FTObjectLibrary
add Subroutine
16 statements
Source File
public subroutine add(self, obj)
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
class(FTObject), POINTER :: obj
Calls
Called By
All Procedures
add addDoublePrecisionValueForKey addIntegerValueForKey addLogicalValueForKey addObjectForKey addObjectsFromList addObjectToArray addObjectToMultiIndexTableForKeys addObjectToSparseMatrixForKeys addQuadValueForKey addRealValueForKey addStringValueForKey AllKeys allLinkedListObjects AllObjects allocatedSize arrayClassName assertWithinToleranceTwoQuad b3hs_hash_key_jenkins basicTests caseSensitive cast cast cast cast cast cast cast castDictionaryToValueDictionary castObjectToLinkedList castObjectToMatrixData castObjectToMultiIndexMatrixData castObjectToValueDictionary castToDictionary castToException castToMutableObjectArray castToValue catch chunkSize className containsKey COUNT dataClassName dataIsOfType dataType demonstrateLinkedList destructException destructFTDictionary destructFTExceptions destructFTKeyObjectPair destructFTLinkedList destructFTLinkedListRecord destructFTObject destructIterator destructMatrixData destructMultiIndexMatrixData destructMultiIndexTable destructObjectArray destructSparseMatrix destructValue detachSharedAssertionsManager dictionaryClassName dictionaryFromObject doublePrecisionValue doublePrecisionValueForKey errorCount errorObject exceptionClassName exceptionFromObject exceptionName finalizeSharedAssertionsManager FTAssert FTAssertEqual FTDictionaryClassTests FTDictionaryDescription FTExceptionClassTests FTKeyObjectPairDescription FTLinkedListClassTests FTLinkedListCurrentRecord FTLinkedListDescription FTLinkedListIsAtEnd FTLinkedListObject FTObjectDescription FTValueClassTests FTValueDescription FTValueDictionaryClassTests Hash1 Hash2 HashTableTests infoDictionary init initAssertionFailureException initEmpty initFatalException initFTException initFTLinkedList initFTObject initFTStack initializeFTExceptions initializeSharedAssertionsManager initMultiIndexTableWithSize initObjectArrayWithSize initSparseMatrixWithSize initWarningException initWithDataOfType initWithDoublePrecision initWithFTLinkedList initWithInteger initWithLogical initWithObject initWithObjectAndKey initWithObjectAndKey initWithObjectAndKeys initWithQuad initWithReal initWithSize initWithString insertObjectAfterObject insertObjectAfterRecord integerValue integerValueForKey isCircular isEqual isUnreferenced key keysMatch linkedListClassName linkedListFromObject linkedListIteratorClassName llRecordClassName logicalValue logicalValueForKey makeCircular matrixDataCast moveToNext MultiIndexMatrixDataCast MultiIndexTableContainsKeys MultiIndexTableFromObject MultiIndexTableSize MultiIndexTableTests MutableArrayClassTests numberOfAssertionFailures numberOfAssertions numberOfItems numberOfRecords object objectArrayFromObject objectAtIndex objectForKey objectForKeyInList objectInMultiIndexTableForKeys objectInSparseMatrixForKeys peek peekLastException pop popLastException printAllExceptions printArray printFTDictionaryDescription printFTExceptionDescription printFTKeyObjectPairDescription printFTLinkedListDescription printFTLinkedRecordDescription printFTObjectDescription printMultiIndexTableDescription printStackDescription printValueDescription push quadValue quadValueForKey realValue realValueForKey refCount release release release release release release release release release release release release release releaseFTData releaseFTDictionary releaseFTException releaseFTKeyObjectPair releaseFTLinkedList releaseFTLinkedListIterator releaseFTLinkedListRecord releaseFTMultiIndexTable releaseFTMutableObjectArray releaseFTObject releaseFTSparseMatrix releaseFTStack releaseFTValue releaseFTValueDictionary releaseMemberDictionary releaseMemberList releaseSMMemberList removeAllLinkedListObjects removeCurrentRecord removeLinkedListRecord removeObject removeObject1 removeObjectAtIndex replaceObjectAtIndexWithObject retainFTObject returnLinkedList reverseLinkedList setCaseSensitive setChunkSize setCurrentError setInfoDictionary setLinkedList setToStart severity sharedAssertionsManager sortKeysAscending SparseMatrixContainsKeys SparseMatrixFromObject SparseMatrixSize SparseMatrixTests stackClassName StackClassTests stackFromObject storedData stringValue stringValueForKey subroutineThatThrowsError testAppendingLists TestDeletingObjects testException testStackInit testStackPush throw valueClassName valueDictionaryClassName valueDictionaryFromDictionary valueDictionaryFromObject valueFromObject
Call graph
add calls initwithobject
initwithobject calls init, retain
basictests calls add
testappendinglists calls add, addobjectsfromlist
insertobjectafterobject calls add
testdeletingobjects calls add
addobjectforkey calls add
addobjecttomultiindextableforkeys calls add
demonstratelinkedlist calls add, insertobjectafterobject
addobjectsfromlist calls add
addobjecttosparsematrixforkeys calls add
ftlinkedlistclasstests calls basictests, testappendinglists, testdeletingobjects
ftdictionaryclasstests calls addobjectforkey
addquadvalueforkey calls addobjectforkey
addstringvalueforkey calls addobjectforkey
initassertionfailureexception calls addobjectforkey
addintegervalueforkey calls addobjectforkey
addrealvalueforkey calls addobjectforkey
adddoubleprecisionvalueforkey calls addobjectforkey
addlogicalvalueforkey calls addobjectforkey