releaseFTObject – FTObjectLibrary
releaseFTObject Subroutine
18 statements
Source File
public subroutine releaseFTObject(self)
 releaseFTObject decreases the reference count by one and implies
 relinquishing ownership by the caller. Call this if control
 over the existence of an object pointer is no longer desired by the caller.
 When the reference count goes to zero, the destructor of the object
 is called automatically and the object is deallocated.
Arguments
Type Intent Optional Attributes Name
class(FTObject), POINTER :: self
Calls
Called By
All Procedures
add addDoublePrecisionValueForKey addIntegerValueForKey addLogicalValueForKey addObjectForKey addObjectsFromList addObjectToArray addObjectToMultiIndexTableForKeys addObjectToSparseMatrixForKeys addQuadValueForKey addRealValueForKey addStringValueForKey AllKeys allLinkedListObjects AllObjects allocatedSize arrayClassName assertWithinToleranceTwoQuad b3hs_hash_key_jenkins basicTests caseSensitive cast cast cast cast cast cast cast castDictionaryToValueDictionary castObjectToLinkedList castObjectToMatrixData castObjectToMultiIndexMatrixData castObjectToValueDictionary castToDictionary castToException castToMutableObjectArray castToValue catch chunkSize className containsKey COUNT dataClassName dataIsOfType dataType demonstrateLinkedList destructException destructFTDictionary destructFTExceptions destructFTKeyObjectPair destructFTLinkedList destructFTLinkedListRecord destructFTObject destructIterator destructMatrixData destructMultiIndexMatrixData destructMultiIndexTable destructObjectArray destructSparseMatrix destructValue detachSharedAssertionsManager dictionaryClassName dictionaryFromObject doublePrecisionValue doublePrecisionValueForKey errorCount errorObject exceptionClassName exceptionFromObject exceptionName finalizeSharedAssertionsManager FTAssert FTAssertEqual FTDictionaryClassTests FTDictionaryDescription FTExceptionClassTests FTKeyObjectPairDescription FTLinkedListClassTests FTLinkedListCurrentRecord FTLinkedListDescription FTLinkedListIsAtEnd FTLinkedListObject FTObjectDescription FTValueClassTests FTValueDescription FTValueDictionaryClassTests Hash1 Hash2 HashTableTests infoDictionary init initAssertionFailureException initEmpty initFatalException initFTException initFTLinkedList initFTObject initFTStack initializeFTExceptions initializeSharedAssertionsManager initMultiIndexTableWithSize initObjectArrayWithSize initSparseMatrixWithSize initWarningException initWithDataOfType initWithDoublePrecision initWithFTLinkedList initWithInteger initWithLogical initWithObject initWithObjectAndKey initWithObjectAndKey initWithObjectAndKeys initWithQuad initWithReal initWithSize initWithString insertObjectAfterObject insertObjectAfterRecord integerValue integerValueForKey isCircular isEqual isUnreferenced key keysMatch linkedListClassName linkedListFromObject linkedListIteratorClassName llRecordClassName logicalValue logicalValueForKey makeCircular matrixDataCast moveToNext MultiIndexMatrixDataCast MultiIndexTableContainsKeys MultiIndexTableFromObject MultiIndexTableSize MultiIndexTableTests MutableArrayClassTests numberOfAssertionFailures numberOfAssertions numberOfItems numberOfRecords object objectArrayFromObject objectAtIndex objectForKey objectForKeyInList objectInMultiIndexTableForKeys objectInSparseMatrixForKeys peek peekLastException pop popLastException printAllExceptions printArray printFTDictionaryDescription printFTExceptionDescription printFTKeyObjectPairDescription printFTLinkedListDescription printFTLinkedRecordDescription printFTObjectDescription printMultiIndexTableDescription printStackDescription printValueDescription push quadValue quadValueForKey realValue realValueForKey refCount release release release release release release release release release release release release release releaseFTData releaseFTDictionary releaseFTException releaseFTKeyObjectPair releaseFTLinkedList releaseFTLinkedListIterator releaseFTLinkedListRecord releaseFTMultiIndexTable releaseFTMutableObjectArray releaseFTObject releaseFTSparseMatrix releaseFTStack releaseFTValue releaseFTValueDictionary releaseMemberDictionary releaseMemberList releaseSMMemberList removeAllLinkedListObjects removeCurrentRecord removeLinkedListRecord removeObject removeObject1 removeObjectAtIndex replaceObjectAtIndexWithObject retainFTObject returnLinkedList reverseLinkedList setCaseSensitive setChunkSize setCurrentError setInfoDictionary setLinkedList setToStart severity sharedAssertionsManager sortKeysAscending SparseMatrixContainsKeys SparseMatrixFromObject SparseMatrixSize SparseMatrixTests stackClassName StackClassTests stackFromObject storedData stringValue stringValueForKey subroutineThatThrowsError testAppendingLists TestDeletingObjects testException testStackInit testStackPush throw valueClassName valueDictionaryClassName valueDictionaryFromDictionary valueDictionaryFromObject valueFromObject
Call graph
releaseftobject calls printdescription, destruct
releaseftdata calls releaseftobject
addobjecttomultiindextableforkeys calls releaseftobject
replaceobjectatindexwithobject calls releaseftobject
releaseftkeyobjectpair calls releaseftobject
destructftkeyobjectpair calls releaseftobject
releaseftmutableobjectarray calls releaseftobject
removeobjectatindex calls releaseftobject
releaseftlinkedlistrecord calls releaseftobject
destructmultiindexmatrixdata calls releaseftobject
releaseftvalue calls releaseftobject
releasesmmemberlist calls releaseftobject
releaseftmultiindextable calls releaseftobject
destructmatrixdata calls releaseftobject
addobjecttosparsematrixforkeys calls releaseftobject
destructobjectarray calls releaseftobject
releaseftsparsematrix calls releaseftobject
destructftlinkedlistrecord calls releaseftobject
release calls releaseftdata, releaseftkeyobjectpair, releaseftmutableobjectarray, releaseftlinkedlistrecord, releaseftvalue, releaseftmultiindextable, releaseftsparsematrix
mutablearrayclasstests calls replaceobjectatindexwithobject, removeobjectatindex, release
removeobject1 calls releaseftlinkedlistrecord
removealllinkedlistobjects calls releaseftlinkedlistrecord
removelinkedlistrecord calls releaseftlinkedlistrecord
ftdictionaryclasstests calls release
addlogicalvalueforkey calls release
addquadvalueforkey calls release
stackclasstests calls release, teststackpush
testdeletingobjects calls release
addintegervalueforkey calls release
ftvalueclasstests calls release
hashtabletests calls release
demonstratelinkedlist calls release
teststackpush calls release
addstringvalueforkey calls release
adddoubleprecisionvalueforkey calls release
addrealvalueforkey calls release
ftlinkedlistclasstests calls testdeletingobjects
destructsparsematrix calls releasesmmemberlist
multiindextabletests calls release
sparsematrixtests calls release