FTAssertEqual – FTObjectLibrary
FTAssertEqual Interface
14 statements
Source File
public interface FTAssertEqual
Calls
Called By
Module Procedures
assertEqualTwoIntegers assertEqualTwoIntegerArrays1D assertEqualTwoIntegerArrays2D assertWithinToleranceTwoReal assertWithinToleranceTwoRealArrays1D assertWithinToleranceTwoRealArrays2D assertWithinToleranceTwoDouble assertWithinToleranceTwoDoubleArrays1D assertWithinToleranceTwoDoubleArrays2D assertWithinToleranceTwoQuad assertEqualTwoLogicals assertEqualString
Module Procedures
private subroutine assertEqualTwoIntegers(expectedValue, actualValue, msg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: expectedValue
integer, intent(in) :: actualValue
character(len=*), optional :: msg
private subroutine assertEqualTwoIntegerArrays1D(expectedValue, actualValue)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), DIMENSION(:) :: expectedValue
integer, intent(in), DIMENSION(:) :: actualValue
private subroutine assertEqualTwoIntegerArrays2D(expectedValue, actualValue)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), DIMENSION(:,:) :: expectedValue
integer, intent(in), DIMENSION(:,:) :: actualValue
private subroutine assertWithinToleranceTwoReal(expectedValue, actualValue, tol, msg)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: expectedValue
real, intent(in) :: actualValue
real, intent(in) :: tol
character(len=*), optional :: msg
private subroutine assertWithinToleranceTwoRealArrays1D(expectedValue, actualValue, tol, msg)
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(:) :: expectedValue
real, intent(in), DIMENSION(:) :: actualValue
real, intent(in) :: tol
character(len=*), optional :: msg
private subroutine assertWithinToleranceTwoRealArrays2D(expectedValue, actualValue, tol)
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(:,:) :: expectedValue
real, intent(in), DIMENSION(:,:) :: actualValue
real, intent(in) :: tol
private subroutine assertWithinToleranceTwoDouble(expectedValue, actualValue, tol, msg)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: expectedValue
double precision, intent(in) :: actualValue
double precision, intent(in) :: tol
character(len=*), optional :: msg
private subroutine assertWithinToleranceTwoDoubleArrays1D(expectedValue, actualValue, tol, msg)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in), DIMENSION(:) :: expectedValue
double precision, intent(in), DIMENSION(:) :: actualValue
double precision, intent(in) :: tol
character(len=*), optional :: msg
private subroutine assertWithinToleranceTwoDoubleArrays2D(expectedValue, actualValue, tol)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in), DIMENSION(:,:) :: expectedValue
double precision, intent(in), DIMENSION(:,:) :: actualValue
double precision, intent(in) :: tol
public subroutine assertWithinToleranceTwoQuad(expectedValue, actualValue, tol, msg)
Arguments
Type Intent Optional Attributes Name
real(kind=SELECTED_REAL_KIND(QUAD_DIGITS)), intent(in) :: expectedValue
real(kind=SELECTED_REAL_KIND(QUAD_DIGITS)), intent(in) :: actualValue
real(kind=SELECTED_REAL_KIND(QUAD_DIGITS)), intent(in) :: tol
character(len=*), optional :: msg
private subroutine assertEqualTwoLogicals(expectedValue, actualValue, msg)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: expectedValue
logical, intent(in) :: actualValue
character(len=*), optional :: msg
private subroutine assertEqualString(expectedValue, actualValue, msg)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: expectedValue
character(len=*) :: actualValue
character(len=*), optional :: msg
All Procedures
add addDoublePrecisionValueForKey addIntegerValueForKey addLogicalValueForKey addObjectForKey addObjectsFromList addObjectToArray addObjectToMultiIndexTableForKeys addObjectToSparseMatrixForKeys addQuadValueForKey addRealValueForKey addStringValueForKey AllKeys allLinkedListObjects AllObjects allocatedSize arrayClassName assertWithinToleranceTwoQuad b3hs_hash_key_jenkins basicTests caseSensitive cast cast cast cast cast cast cast castDictionaryToValueDictionary castObjectToLinkedList castObjectToMatrixData castObjectToMultiIndexMatrixData castObjectToValueDictionary castToDictionary castToException castToMutableObjectArray castToValue catch chunkSize className containsKey COUNT dataClassName dataIsOfType dataType demonstrateLinkedList destructException destructFTDictionary destructFTExceptions destructFTKeyObjectPair destructFTLinkedList destructFTLinkedListRecord destructFTObject destructIterator destructMatrixData destructMultiIndexMatrixData destructMultiIndexTable destructObjectArray destructSparseMatrix destructValue detachSharedAssertionsManager dictionaryClassName dictionaryFromObject doublePrecisionValue doublePrecisionValueForKey errorCount errorObject exceptionClassName exceptionFromObject exceptionName finalizeSharedAssertionsManager FTAssert FTAssertEqual FTDictionaryClassTests FTDictionaryDescription FTExceptionClassTests FTKeyObjectPairDescription FTLinkedListClassTests FTLinkedListCurrentRecord FTLinkedListDescription FTLinkedListIsAtEnd FTLinkedListObject FTObjectDescription FTValueClassTests FTValueDescription FTValueDictionaryClassTests Hash1 Hash2 HashTableTests infoDictionary init initAssertionFailureException initEmpty initFatalException initFTException initFTLinkedList initFTObject initFTStack initializeFTExceptions initializeSharedAssertionsManager initMultiIndexTableWithSize initObjectArrayWithSize initSparseMatrixWithSize initWarningException initWithDataOfType initWithDoublePrecision initWithFTLinkedList initWithInteger initWithLogical initWithObject initWithObjectAndKey initWithObjectAndKey initWithObjectAndKeys initWithQuad initWithReal initWithSize initWithString insertObjectAfterObject insertObjectAfterRecord integerValue integerValueForKey isCircular isEqual isUnreferenced key keysMatch linkedListClassName linkedListFromObject linkedListIteratorClassName llRecordClassName logicalValue logicalValueForKey makeCircular matrixDataCast moveToNext MultiIndexMatrixDataCast MultiIndexTableContainsKeys MultiIndexTableFromObject MultiIndexTableSize MultiIndexTableTests MutableArrayClassTests numberOfAssertionFailures numberOfAssertions numberOfItems numberOfRecords object objectArrayFromObject objectAtIndex objectForKey objectForKeyInList objectInMultiIndexTableForKeys objectInSparseMatrixForKeys peek peekLastException pop popLastException printAllExceptions printArray printFTDictionaryDescription printFTExceptionDescription printFTKeyObjectPairDescription printFTLinkedListDescription printFTLinkedRecordDescription printFTObjectDescription printMultiIndexTableDescription printStackDescription printValueDescription push quadValue quadValueForKey realValue realValueForKey refCount release release release release release release release release release release release release release releaseFTData releaseFTDictionary releaseFTException releaseFTKeyObjectPair releaseFTLinkedList releaseFTLinkedListIterator releaseFTLinkedListRecord releaseFTMultiIndexTable releaseFTMutableObjectArray releaseFTObject releaseFTSparseMatrix releaseFTStack releaseFTValue releaseFTValueDictionary releaseMemberDictionary releaseMemberList releaseSMMemberList removeAllLinkedListObjects removeCurrentRecord removeLinkedListRecord removeObject removeObject1 removeObjectAtIndex replaceObjectAtIndexWithObject retainFTObject returnLinkedList reverseLinkedList setCaseSensitive setChunkSize setCurrentError setInfoDictionary setLinkedList setToStart severity sharedAssertionsManager sortKeysAscending SparseMatrixContainsKeys SparseMatrixFromObject SparseMatrixSize SparseMatrixTests stackClassName StackClassTests stackFromObject storedData stringValue stringValueForKey subroutineThatThrowsError testAppendingLists TestDeletingObjects testException testStackInit testStackPush throw valueClassName valueDictionaryClassName valueDictionaryFromDictionary valueDictionaryFromObject valueFromObject
Call graph
ftassertequal calls assertwithintolerancetwoquad
assertwithintolerancetwoquad calls isequal, initializesharedassertionsmanager
ftdictionaryclasstests calls ftassertequal
sparsematrixtests calls ftassertequal
ftexceptionclasstests calls ftassertequal
ftvalueclasstests calls ftassertequal
basictests calls ftassertequal
stackclasstests calls ftassertequal, teststackpush, teststackinit
testdeletingobjects calls ftassertequal
multiindextabletests calls ftassertequal
testappendinglists calls ftassertequal
ftvaluedictionaryclasstests calls ftassertequal
hashtabletests calls ftassertequal
teststackpush calls ftassertequal
teststackinit calls ftassertequal
mutablearrayclasstests calls ftassertequal
ftlinkedlistclasstests calls basictests, testdeletingobjects, testappendinglists