addDoublePrecisionValueForKey – FTObjectLibrary
addDoublePrecisionValueForKey Subroutine
13 statements
Source File
public subroutine addDoublePrecisionValueForKey(self, r, key)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
double precision :: r
character(len=*) :: key
Calls
Call graph
adddoubleprecisionvalueforkey calls release, initwithvalue, addobjectforkey
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
initwithquad calls initftobject
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount