addObjectToSparseMatrixForKeys – FTObjectLibrary
addObjectToSparseMatrixForKeys Subroutine
15 statements
Source File
public subroutine addObjectToSparseMatrixForKeys(self, obj, i, j)
Type Bound
FTSparseMatrix
Arguments
Type Intent Optional Attributes Name
class(FTSparseMatrix) :: self
class(FTObject), POINTER :: obj
integer :: i
integer :: j
Calls
Call graph
addobjecttosparsematrixforkeys calls add, initwithobjectandkey, releaseftobject, sparsematrixcontainskeys
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
releaseftobject calls printftobjectdescription
sparsematrixcontainskeys calls cast, ftlinkedlistisatend, ftlinkedlistobject, movetonext, setlinkedlist, settostart
cast calls castobjecttomatrixdata
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount
setlinkedlist calls retainftobject, settostart, releasememberlist
releasememberlist calls releaseftobject