addObjectToArray – FTObjectLibrary
addObjectToArray Subroutine
11 statements
Source File
public subroutine addObjectToArray(self, obj)
Add an object to the end of the array
*Usage
  CLASS(FTMutableObjectArray)      :: array
  CLASS(FTObject)        , POINTER :: obj
  CLASS(FTObjectSubclass), POINTER :: p
  obj => p
  CALL array % addObject(obj)
Type Bound
FTMutableObjectArray
Arguments
Type Intent Optional Attributes Name
class(FTMutableObjectArray) :: self
class(FTObject), POINTER :: obj
Calls
Called by
Call graph
addobjecttoarray calls retainftobject
alllinkedlistobjects calls addobjecttoarray
allobjects calls addobjecttoarray