addObjectsFromList – FTObjectLibrary
addObjectsFromList Subroutine
18 statements
Source File
public subroutine addObjectsFromList(self, list)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
class(FTLinkedList), POINTER :: list
Calls
Call graph
addobjectsfromlist calls add, iscircular, makecircular
add calls initwithobject
initwithobject calls initftobject, retainftobject