addQuadValueForKey – FTObjectLibrary
addQuadValueForKey Subroutine
13 statements
Source File
public subroutine addQuadValueForKey(self, r, key)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
real(kind=SELECTED_REAL_KIND(QUAD_DIGITS)) :: r
character(len=*) :: key
Calls
Called by
Call graph
addquadvalueforkey calls release, initwithvalue, addobjectforkey
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
initwithquad calls initftobject
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount
initassertionfailureexception calls addvalueforkey
initfatalexception calls addvalueforkey
initwarningexception calls addvalueforkey