AddString – FTObjectLibrary
AddString Subroutine
11 statements
Source File
public subroutine AddString(self, str)
AddString adds a string to the set if it is not already present
Usage:
    CALL set % addString(str)
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
character(len=*) :: str
Calls
Called by
Call graph
addstring calls release, addobjectforkey, containskey, initftobject
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
containskey calls objectforkey
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
objectforkey calls b3hs_hash_key_jenkins
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount
initwithstrings calls addstring
intersectionwithset calls addstring
setfromdifference calls addstring
unionwithset calls addstring, initwithstrings