addStringValueForKey – FTObjectLibrary
addStringValueForKey Subroutine
13 statements
Source File
public subroutine addStringValueForKey(self, s, key)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
character(len=*) :: s
character(len=*) :: key
Calls
Call graph
addstringvalueforkey calls release, initwithvalue, addobjectforkey
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
initwithquad calls initftobject
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount