allLinkedListObjects – FTObjectLibrary
allLinkedListObjects Function
26 statements
Source File
public function allLinkedListObjects(self) result(array)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
Return Value class(FTMutableObjectArray), POINTER
Calls
Call graph
alllinkedlistobjects calls addobjecttoarray, initobjectarraywithsize, makecircular
addobjecttoarray calls retainftobject
initobjectarraywithsize calls initftobject