AllObjects – FTObjectLibrary
AllObjects Function
24 statements
Source File
public function AllObjects(self) result(objectArray)
Type Bound
FTDictionary
Arguments
Type Intent Optional Attributes Name
class(FTDictionary) :: self
Return Value class(FTMutableObjectArray), POINTER
Calls
Call graph
allobjects calls key, object, addobjecttoarray, initobjectarraywithsize
addobjecttoarray calls retainftobject
initobjectarraywithsize calls initftobject