b3hs_hash_key_jenkins – FTObjectLibrary
b3hs_hash_key_jenkins Function
78 statements
Source File
public function b3hs_hash_key_jenkins(key, range) result(code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: key
integer, intent(in) :: range
Return Value integer
Called by
Call graph
addobjectforkey calls b3hs_hash_key_jenkins
objectforkey calls b3hs_hash_key_jenkins
adddoubleprecisionvalueforkey calls addobjectforkey
addintegervalueforkey calls addobjectforkey
addlogicalvalueforkey calls addobjectforkey
addquadvalueforkey calls addobjectforkey
addrealvalueforkey calls addobjectforkey
addstring calls addobjectforkey, containskey
addstringvalueforkey calls addobjectforkey
containskey calls objectforkey
doubleprecisionvalueforkey calls objectforkey
initassertionfailureexception calls addobjectforkey, addvalueforkey
integervalueforkey calls objectforkey
logicalvalueforkey calls objectforkey
quadvalueforkey calls objectforkey
realvalueforkey calls objectforkey
stringvalueforkeya calls objectforkey
stringvalueforkeyr calls objectforkey
containsstring calls containskey
initwithstrings calls addstring
intersectionwithset calls addstring, containsstring
setfromdifference calls addstring, containsstring
unionwithset calls addstring, initwithstrings
initfatalexception calls addvalueforkey
initwarningexception calls addvalueforkey