castToMutableObjectArray – FTObjectLibrary
castToMutableObjectArray Subroutine
11 statements
Source File
public subroutine castToMutableObjectArray(obj, cast)
Arguments
Type Intent Optional Attributes Name
class(FTObject), POINTER :: obj
class(FTMutableObjectArray), POINTER :: cast
Called by
Call graph
cast calls casttomutableobjectarray
peeklastexception calls cast
poplastexception calls cast
printallexceptions calls cast
destructftexceptions calls printallexceptions