castObjectToMultiIndexMatrixData – FTObjectLibrary
castObjectToMultiIndexMatrixData Subroutine
11 statements
Source File
public subroutine castObjectToMultiIndexMatrixData(obj, cast)
Arguments
Type Intent Optional Attributes Name
class(FTObject), POINTER :: obj
class(MultiIndexMatrixData), POINTER :: cast
Called by
Call graph
cast calls castobjecttomultiindexmatrixdata
multiindextablecontainskeys calls cast
objectinmultiindextableforkeys calls cast
addobjecttomultiindextableforkeys calls multiindextablecontainskeys