containsString – FTObjectLibrary
containsString Function
6 statements
Source File
public function containsString(self, str)
containsString returns .TRUE. if the set contains the string, .FALSE. otherwise.
Usage:
    if(set % containsString(str))
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
character(len=*) :: str
Return Value logical
Calls
Called by
Call graph
containsstring calls containskey
containskey calls objectforkey
objectforkey calls b3hs_hash_key_jenkins
intersectionwithset calls containsstring
setfromdifference calls containsstring