destructFTExceptions – FTObjectLibrary
destructFTExceptions Subroutine
20 statements
Source File
public subroutine destructFTExceptions()
Called at the end of execution. This procedure will announce if there are uncaught exceptions raised and print them.
Arguments
None
Calls
Call graph
destructftexceptions calls catch, printallexceptions, releasecurrenterror, releaseftobject
printallexceptions calls cast, ftlinkedlistisatend, ftlinkedlistobject, initwithftlinkedlist, movetonext, printftexceptiondescription, settostart
releasecurrenterror calls releaseftobject
releaseftobject calls printftobjectdescription
cast calls casttomutableobjectarray
initwithftlinkedlist calls settostart, initftobject, setlinkedlist
printftexceptiondescription calls exceptionname, infodictionary, printftdictionarydescription
printftobjectdescription calls refcount
printftdictionarydescription calls printftlinkedlistdescription
setlinkedlist calls settostart, releasememberlist, retainftobject
printftlinkedlistdescription calls makecircular, printftlinkedrecorddescription
releasememberlist calls releaseftobject
printftlinkedrecorddescription calls printftobjectdescription