destructFTLinkedList – FTObjectLibrary
destructFTLinkedList Subroutine
5 statements
Source File
public subroutine destructFTLinkedList(self)
It is automatically called by release().
Arguments
Type Intent Optional Attributes Name
type(FTLinkedList) :: self
Calls
Call graph
destructftlinkedlist calls removealllinkedlistobjects
removealllinkedlistobjects calls release, iscircular, makecircular
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount