destructIterator – FTObjectLibrary
destructIterator Subroutine
6 statements
Source File
public subroutine destructIterator(self)
Arguments
Type Intent Optional Attributes Name
type(FTLinkedListIterator) :: self
Calls
Call graph
destructiterator calls releasememberlist
releasememberlist calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount