destructObjectArray – FTObjectLibrary
destructObjectArray Subroutine
13 statements
Source File
public recursive subroutine destructObjectArray(self)
Destructor for the class. This is called automatically when the reference count reaches zero. Do not call this yourself.
Arguments
Type Intent Optional Attributes Name
type(FTMutableObjectArray) :: self
Calls
Call graph
destructobjectarray calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount