doublePrecisionValueForKey – FTObjectLibrary
doublePrecisionValueForKey Function
14 statements
Source File
public function doublePrecisionValueForKey(self, key)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
character(len=*) :: key
Return Value doubleprecision
Calls
Call graph
doubleprecisionvalueforkey calls doubleprecisionvalue, objectforkey, valuefromobject
objectforkey calls b3hs_hash_key_jenkins