errorCount – FTObjectLibrary
errorCount Function
7 statements
Source File
public function errorCount()
Returns the number of exceptions that have been thrown.
Arguments
None
Return Value integer
Calls
Call graph
errorcount calls initializeftexceptions
initializeftexceptions calls initftstack
initftstack calls initftlinkedlist
initftlinkedlist calls initftobject