FTLinkedListIsAtEnd – FTObjectLibrary
FTLinkedListIsAtEnd Function
9 statements
Source File
public function FTLinkedListIsAtEnd(self)
Type Bound
FTLinkedListIterator
Arguments
Type Intent Optional Attributes Name
class(FTLinkedListIterator) :: self
Return Value logical
Called by
Call graph
objectinsparsematrixforkeys calls ftlinkedlistisatend
printallexceptions calls ftlinkedlistisatend
sparsematrixcontainskeys calls ftlinkedlistisatend
addobjecttosparsematrixforkeys calls sparsematrixcontainskeys
destructftexceptions calls printallexceptions