FTObjectDescription – FTObjectLibrary
FTObjectDescription Function
7 statements
Source File
public function FTObjectDescription(self)
Returns a character string of length DESCRIPTION_CHARACTER_LENGTH that represents the object. the base class implementation returns an empty string. Note that if the description is too long, the expected string will be truncated. In general, one wants to use printDescription.
Type Bound
FTObject
Arguments
Type Intent Optional Attributes Name
class(FTObject) :: self
Return Value character(len=DESCRIPTION_CHARACTER_LENGTH)
Calls
Called by
Call graph
ftobjectdescription calls refcount
ftkeyobjectpairdescription calls ftobjectdescription
ftlinkedlistdescription calls ftobjectdescription
ftdictionarydescription calls ftlinkedlistdescription