initFTException – FTObjectLibrary
initFTException Subroutine
14 statements
Source File
public subroutine initFTException(self, severity, exceptionName, infoDictionary)
The main initializer for the class
Type Bound
FTException
Arguments
Type Intent Optional Attributes Name
class(FTException) :: self
integer :: severity
character(len=*) :: exceptionName
class(FTDictionary), optional, POINTER :: infoDictionary
Calls
Called by
Call graph
initftexception calls initftobject, setinfodictionary
setinfodictionary calls releasememberdictionary, retainftobject
releasememberdictionary calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
initassertionfailureexception calls initftexception
initfatalexception calls initftexception
initwarningexception calls initftexception