initFTObject – FTObjectLibrary
initFTObject Subroutine
5 statements
Source File
public subroutine initFTObject(self)
Generic Name: init()
Initializes the object. The base class initialization does nothing but set the reference count to one.
Type Bound
FTObject
Arguments
Type Intent Optional Attributes Name
class(FTObject) :: self
Called by
Call graph
addstring calls initftobject, addobjectforkey
initempty calls initftobject
initftexception calls initftobject
initftlinkedlist calls initftobject
initftstringset calls initftobject, initwithsize
initmultiindextablewithsize calls initftobject
initobjectarraywithsize calls initftobject
initsparsematrixwithsize calls initftobject
initwithdataoftype calls initftobject
initwithdoubleprecision calls initftobject
initwithftlinkedlist calls initftobject
initwithinteger calls initftobject
initwithlogical calls initftobject
initwithobject calls initftobject
initwithobjectandkey calls initftobject
initwithobjectandkeys calls initftobject
initwithquad calls initftobject
initwithreal calls initftobject
initwithsize calls initftobject
initwithstring calls initftobject
add calls initwithobject
addobjectforkey calls initwithobjectandkey, add
addobjecttomultiindextableforkeys calls initwithobjectandkeys, add
addobjecttosparsematrixforkeys calls initwithobjectandkey, add
alllinkedlistobjects calls initobjectarraywithsize
allobjects calls initobjectarraywithsize
init calls initwithsize
initassertionfailureexception calls initftexception, initwithsize, addobjectforkey, addvalueforkey
initfatalexception calls initftexception, initwithsize, addvalueforkey
initftstack calls initftlinkedlist
initwarningexception calls initftexception, initwithsize, addvalueforkey
initwithstrings calls addstring, initftstringset
insertobjectafterrecord calls initwithobject
intersectionwithset calls addstring, initftstringset
printallexceptions calls initwithftlinkedlist
push calls initwithobject
setfromdifference calls addstring, initftstringset
unionwithset calls addstring, initwithstrings
adddoubleprecisionvalueforkey calls initwithvalue, addobjectforkey
addintegervalueforkey calls initwithvalue, addobjectforkey
addlogicalvalueforkey calls initwithvalue, addobjectforkey
addobjectsfromlist calls add
addquadvalueforkey calls initwithvalue, addobjectforkey
addrealvalueforkey calls initwithvalue, addobjectforkey
addstringvalueforkey calls initwithvalue, addobjectforkey
destructftexceptions calls printallexceptions
initializeftexceptions calls initftstack
insertobjectafterobject calls add, insertobjectafterrecord
throw calls push, initializeftexceptions
errorcount calls initializeftexceptions
errorobject calls initializeftexceptions
maximumerrorseverity calls initializeftexceptions
peeklastexception calls initializeftexceptions
poplastexception calls initializeftexceptions