initWithFTLinkedList – FTObjectLibrary
initWithFTLinkedList Subroutine
10 statements
Source File
public subroutine initWithFTLinkedList(self, list)
Type Bound
FTLinkedListIterator
Arguments
Type Intent Optional Attributes Name
class(FTLinkedListIterator) :: self
class(FTLinkedList), POINTER :: list
Calls
Called by
Call graph
initwithftlinkedlist calls initftobject, setlinkedlist, settostart
setlinkedlist calls settostart, releasememberlist, retainftobject
releasememberlist calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
printallexceptions calls initwithftlinkedlist
destructftexceptions calls printallexceptions