initWithObjectAndKey – FTObjectLibrary
initWithObjectAndKey Subroutine
10 statements
Source File
public subroutine initWithObjectAndKey(self, v, key)
Type Bound
FTKeyObjectPair
Arguments
Type Intent Optional Attributes Name
class(FTKeyObjectPair) :: self
class(FTObject), POINTER :: v
character(len=*) :: key
Calls
Called by
Call graph
initwithobjectandkey calls initftobject, retainftobject
addobjectforkey calls initwithobjectandkey
adddoubleprecisionvalueforkey calls addobjectforkey
addintegervalueforkey calls addobjectforkey
addlogicalvalueforkey calls addobjectforkey
addquadvalueforkey calls addobjectforkey
addrealvalueforkey calls addobjectforkey
addstring calls addobjectforkey
addstringvalueforkey calls addobjectforkey
initassertionfailureexception calls addobjectforkey, addvalueforkey
initwithstrings calls addstring
intersectionwithset calls addstring
setfromdifference calls addstring
unionwithset calls addstring, initwithstrings
initfatalexception calls addvalueforkey
initwarningexception calls addvalueforkey