initFatalException – FTObjectLibrary
initFatalException Subroutine
13 statements
Source File
public subroutine initFatalException(self, msg)
A convenience initializer for a fatal error that includes the key "message" in the infoDictionary.Use this initializer as an example of how to write one's own exception.
Type Bound
FTException
Arguments
Type Intent Optional Attributes Name
class(FTException) :: self
character(len=*) :: msg
Calls
Call graph
initfatalexception calls addvalueforkey, initftexception, initwithsize, releasememberdictionary
initftexception calls initftobject, setinfodictionary
initwithsize calls initftobject
releasememberdictionary calls releaseftobject
addquadvalueforkey calls release, initwithvalue, addobjectforkey
releaseftobject calls printftobjectdescription
setinfodictionary calls releasememberdictionary, retainftobject
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
printftobjectdescription calls refcount
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
initwithquad calls initftobject
initwithobject calls initftobject, retainftobject