initFTStack – FTObjectLibrary
initFTStack Subroutine
5 statements
Source File
public subroutine initFTStack(self)
Public, generic name: init()
Initialize the stack.
Type Bound
FTStack
Arguments
Type Intent Optional Attributes Name
class(FTStack) :: self
Calls
Called by
Call graph
initftstack calls initftlinkedlist
initftlinkedlist calls initftobject
initializeftexceptions calls initftstack
errorcount calls initializeftexceptions
errorobject calls initializeftexceptions
maximumerrorseverity calls initializeftexceptions
peeklastexception calls initializeftexceptions
poplastexception calls initializeftexceptions
throw calls initializeftexceptions