initWithQuad – FTObjectLibrary
initWithQuad Subroutine
11 statements
Source File
public subroutine initWithQuad(self, v)
Public, generic name: initwithValue()
Initialize the value object with a quad precision number
Type Bound
FTValue
Arguments
Type Intent Optional Attributes Name
class(FTValue) :: self
real(kind=SELECTED_REAL_KIND(QUAD_DIGITS)) :: v
Calls
Called by
Call graph
initwithquad calls initftobject
adddoubleprecisionvalueforkey calls initwithvalue
addintegervalueforkey calls initwithvalue
addlogicalvalueforkey calls initwithvalue
addquadvalueforkey calls initwithvalue
addrealvalueforkey calls initwithvalue
addstringvalueforkey calls initwithvalue
initassertionfailureexception calls addvalueforkey
initfatalexception calls addvalueforkey
initwarningexception calls addvalueforkey