initFTLinkedList – FTObjectLibrary
initFTLinkedList Subroutine
9 statements
Source File
public subroutine initFTLinkedList(self)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
Calls
Called by
Call graph
initftlinkedlist calls initftobject
initftstack calls initftlinkedlist
initializeftexceptions calls initftstack
errorcount calls initializeftexceptions
errorobject calls initializeftexceptions
maximumerrorseverity calls initializeftexceptions
peeklastexception calls initializeftexceptions
poplastexception calls initializeftexceptions
throw calls initializeftexceptions