initWithStrings – FTObjectLibrary
initWithStrings Subroutine
12 statements
Source File
public subroutine initWithStrings(self, strings)
initializer. Initializes the amount of storage from the strings passed Usage CLASS(FTStringSet) :: FTStringSet CHARACTER(LEN=) :: strings(:) CALL FTStringSet % initWithStrings(strings)
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
character(len=*) :: strings(:)
Calls
Called by
Call graph
initwithstrings calls addstring, initftstringset
addstring calls release, addobjectforkey, containskey, initftobject
initftstringset calls initftobject, initwithsize
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
containskey calls objectforkey
initwithsize calls initftobject
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
objectforkey calls b3hs_hash_key_jenkins
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount
unionwithset calls initwithstrings