initFTStringSet – FTObjectLibrary
initFTStringSet Subroutine
7 statements
Source File
public subroutine initFTStringSet(self, FTStringSetSize)
Designated initializer. Initializes the amount of storage, but the FTStringSet remains empty.
*Usage CLASS(FTStringSet) :: FTStringSet integer :: N = 11 logical :: cs = .true. CALL FTStringSet % initFTStringSet(N)
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
integer :: FTStringSetSize
Calls
Called by
Call graph
initftstringset calls initftobject, initwithsize
initwithsize calls initftobject
initwithstrings calls initftstringset
intersectionwithset calls initftstringset
setfromdifference calls initftstringset
unionwithset calls initwithstrings