insertObjectAfterObject – FTObjectLibrary
insertObjectAfterObject Subroutine
20 statements
Source File
public subroutine insertObjectAfterObject(self, obj, after)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
class(FTObject), POINTER :: obj
class(FTObject), POINTER :: after
Calls
Call graph
insertobjectafterobject calls add, insertobjectafterrecord
add calls initwithobject
insertobjectafterrecord calls initwithobject
initwithobject calls initftobject, retainftobject