intersectionWithSet – FTObjectLibrary
intersectionWithSet Function
17 statements
Source File
public function intersectionWithSet(self, set) result(newSet)
intersectionWithSet returns a pointer to a new set that is the intersection of two sets. the new set has reference count of 1. Release when done.
Usage:
  newSet => set1 % intersectionWithSet(set2)
  ... do something ...
  call releaseFTStringSet(newSet)
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
class(FTStringSet) :: set
Return Value type(FTStringSet), POINTER
Calls
Call graph
intersectionwithset calls addstring, containsstring, initftstringset, strings
addstring calls release, addobjectforkey, containskey, initftobject
containsstring calls containskey
initftstringset calls initftobject, initwithsize
strings calls allkeys
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
allkeys calls key
containskey calls objectforkey
initwithsize calls initftobject
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
objectforkey calls b3hs_hash_key_jenkins
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount