isCircular – FTObjectLibrary
isCircular Function
5 statements
Source File
public function isCircular(self)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
Return Value logical
Called by
Call graph
addobjectsfromlist calls iscircular
removealllinkedlistobjects calls iscircular
removelinkedlistrecord calls iscircular
destructftlinkedlist calls removealllinkedlistobjects
removecurrentrecord calls removelinkedlistrecord
removeobject calls removelinkedlistrecord