makeCircular – FTObjectLibrary
makeCircular Subroutine
14 statements
Source File
public subroutine makeCircular(self, circular)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
logical :: circular
Called by
Call graph
addobjectsfromlist calls makecircular
alllinkedlistobjects calls makecircular
printftlinkedlistdescription calls makecircular
removealllinkedlistobjects calls makecircular
removelinkedlistrecord calls makecircular
reverselinkedlist calls makecircular
destructftlinkedlist calls removealllinkedlistobjects
printftdictionarydescription calls printftlinkedlistdescription
printmultiindextabledescription calls printftlinkedlistdescription
printstackdescription calls printftlinkedlistdescription
removecurrentrecord calls removelinkedlistrecord
removeobject calls removelinkedlistrecord
printftexceptiondescription calls printftdictionarydescription
printallexceptions calls printftexceptiondescription
destructftexceptions calls printallexceptions