objectInMultiIndexTableForKeys – FTObjectLibrary
objectInMultiIndexTableForKeys Function
28 statements
Source File
public function objectInMultiIndexTableForKeys(self, keys) result(r)
Type Bound
FTMultiIndexTable
Arguments
Type Intent Optional Attributes Name
class(FTMultiIndexTable) :: self
integer :: keys(:)
Return Value class(FTObject), POINTER
Calls
Contents
Call graph
objectinmultiindextableforkeys calls cast, keysmatch, sortkeysascending
cast calls castobjecttomultiindexmatrixdata