objectInSparseMatrixForKeys – FTObjectLibrary
objectInSparseMatrixForKeys Function
25 statements
Source File
public function objectInSparseMatrixForKeys(self, i, j) result(r)
Type Bound
FTSparseMatrix
Arguments
Type Intent Optional Attributes Name
class(FTSparseMatrix) :: self
integer :: i
integer :: j
Return Value class(FTObject), POINTER
Calls
Call graph
objectinsparsematrixforkeys calls cast, ftlinkedlistisatend, ftlinkedlistobject, movetonext, setlinkedlist
cast calls castobjecttomatrixdata
setlinkedlist calls releasememberlist, retainftobject, settostart
releasememberlist calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount