peekLastException – FTObjectLibrary
peekLastException Function
11 statements
Source File
public function peekLastException()
Get the last exception posted. This is NOT popped from the stack. The caller does not own the object.
Arguments
None
Return Value class(FTException), POINTER
Calls
Call graph
peeklastexception calls cast, initializeftexceptions, peek
cast calls casttomutableobjectarray
initializeftexceptions calls initftstack
initftstack calls initftlinkedlist
initftlinkedlist calls initftobject