pop – FTObjectLibrary
pop Subroutine
18 statements
Source File
public subroutine pop(self, p)
Type Bound
FTStack
Arguments
Type Intent Optional Attributes Name
class(FTStack) :: self
class(FTObject), POINTER :: p
Calls
Called by
Call graph
pop calls release, retainftobject
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
poplastexception calls pop