popLastException – FTObjectLibrary
popLastException Function
13 statements
Source File
public function popLastException()
Get the last exception posted. This is popped from the stack. The caller is responsible for releasing the object after popping
Arguments
None
Return Value class(FTException), POINTER
Calls
Call graph
poplastexception calls cast, initializeftexceptions, pop
cast calls casttomutableobjectarray
initializeftexceptions calls initftstack
pop calls release, retainftobject
release calls releaseftobject
initftstack calls initftlinkedlist
initftlinkedlist calls initftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount