printStackDescription – FTObjectLibrary
printStackDescription Subroutine
6 statements
Source File
public subroutine printStackDescription(self, iUnit)
Type Bound
FTStack
Arguments
Type Intent Optional Attributes Name
class(FTStack) :: self
integer :: iUnit
Calls
Call graph
printstackdescription calls printftlinkedlistdescription
printftlinkedlistdescription calls makecircular, printftlinkedrecorddescription
printftlinkedrecorddescription calls printftobjectdescription
printftobjectdescription calls refcount