printFTExceptionDescription – FTObjectLibrary
printFTExceptionDescription Subroutine
10 statements
Source File
public subroutine printFTExceptionDescription(self, iUnit)
A basic printing of the exception and the info held in the infoDictionary.
Type Bound
FTException
Arguments
Type Intent Optional Attributes Name
class(FTException) :: self
integer :: iUnit
Calls
Called by
Call graph
printftexceptiondescription calls exceptionname, infodictionary, printftdictionarydescription
printftdictionarydescription calls printftlinkedlistdescription
printftlinkedlistdescription calls makecircular, printftlinkedrecorddescription
printftlinkedrecorddescription calls printftobjectdescription
printftobjectdescription calls refcount
printallexceptions calls printftexceptiondescription
destructftexceptions calls printallexceptions