push – FTObjectLibrary
push Subroutine
19 statements
Source File
public subroutine push(self, obj)
Type Bound
FTStack
Arguments
Type Intent Optional Attributes Name
class(FTStack) :: self
class(FTObject), POINTER :: obj
Calls
Called by
Call graph
push calls initwithobject
initwithobject calls initftobject, retainftobject
throw calls push