quadValueForKey – FTObjectLibrary
quadValueForKey Function
14 statements
Source File
public function quadValueForKey(self, key)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
character(len=*) :: key
Return Value real(kind=selected_real_kind(quad_digits))
Calls
Call graph
quadvalueforkey calls objectforkey, quadvalue, valuefromobject
objectforkey calls b3hs_hash_key_jenkins