realValueForKey – FTObjectLibrary
realValueForKey Function
14 statements
Source File
public function realValueForKey(self, key)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
character(len=*) :: key
Return Value real
Calls
Call graph
realvalueforkey calls objectforkey, realvalue, valuefromobject
objectforkey calls b3hs_hash_key_jenkins