refCount – FTObjectLibrary
refCount Function
5 statements
Source File
public function refCount(self)
Returns the reference count for the object. Normally this is done only for debugging purposes.
Type Bound
FTObject
Arguments
Type Intent Optional Attributes Name
class(FTObject) :: self
Return Value integer
Called by
Call graph
classname calls refcount
dataclassname calls refcount
destructftobject calls refcount
dictionaryclassname calls refcount
exceptionclassname calls refcount
ftobjectdescription calls refcount
printftobjectdescription calls refcount
stackclassname calls refcount
valueclassname calls refcount
valuedictionaryclassname calls refcount
ftkeyobjectpairdescription calls ftobjectdescription
ftlinkedlistdescription calls ftobjectdescription
printarray calls printftobjectdescription
printftkeyobjectpairdescription calls printftobjectdescription
printftlinkedrecorddescription calls printftobjectdescription
releaseftobject calls printftobjectdescription
release calls releaseftobject
addobjecttomultiindextableforkeys calls releaseftobject
addobjecttosparsematrixforkeys calls releaseftobject, sparsematrixcontainskeys
destructftexceptions calls releaseftobject, releasecurrenterror, printallexceptions
destructftkeyobjectpair calls releaseftobject
destructftlinkedlistrecord calls releaseftobject
destructmatrixdata calls releaseftobject
destructmultiindexmatrixdata calls releaseftobject
destructobjectarray calls releaseftobject
ftdictionarydescription calls ftlinkedlistdescription
printftlinkedlistdescription calls printftlinkedrecorddescription
releasecurrenterror calls releaseftobject
releaseftvaluedictionary calls releaseftobject
releasememberdictionary calls releaseftobject
releasememberlist calls releaseftobject
releasesmmemberlist calls releaseftobject
removeobjectatindex calls releaseftobject
replaceobjectatindexwithobject calls releaseftobject
adddoubleprecisionvalueforkey calls release, addobjectforkey
addintegervalueforkey calls release, addobjectforkey
addlogicalvalueforkey calls release, addobjectforkey
addobjectforkey calls release
addquadvalueforkey calls release, addobjectforkey
addrealvalueforkey calls release, addobjectforkey
addstring calls release, addobjectforkey
addstringvalueforkey calls release, addobjectforkey
destructexception calls releasememberdictionary
destructiterator calls releasememberlist
destructsparsematrix calls releasesmmemberlist
initassertionfailureexception calls releasememberdictionary, addobjectforkey, addvalueforkey, initftexception
initfatalexception calls releasememberdictionary, addvalueforkey, initftexception
initwarningexception calls releasememberdictionary, addvalueforkey, initftexception
pop calls release
printftdictionarydescription calls printftlinkedlistdescription
printmultiindextabledescription calls printftlinkedlistdescription
printstackdescription calls printftlinkedlistdescription
releaseftdata calls release
releaseftdictionary calls release
releaseftexception calls release
releaseftkeyobjectpair calls release
releaseftlinkedlist calls release
releaseftlinkedlistiterator calls release
releaseftlinkedlistrecord calls release
releaseftmatrixdata calls release
releaseftmultiindexmatrixdata calls release
releaseftmultiindextable calls release
releaseftmutableobjectarray calls release
releaseftsparsematrix calls release
releaseftstack calls release
releaseftstringset calls release
releaseftvalue calls release
removealllinkedlistobjects calls release
removelinkedlistrecord calls release
setcurrenterror calls releasecurrenterror
setinfodictionary calls releasememberdictionary
setlinkedlist calls releasememberlist
destructftlinkedlist calls removealllinkedlistobjects
initftexception calls setinfodictionary
initwithftlinkedlist calls setlinkedlist
initwithstrings calls addstring
intersectionwithset calls addstring
objectinsparsematrixforkeys calls setlinkedlist
poplastexception calls pop
printftexceptiondescription calls printftdictionarydescription
removecurrentrecord calls removelinkedlistrecord
removeobject calls removelinkedlistrecord
setfromdifference calls addstring
sparsematrixcontainskeys calls setlinkedlist
unionwithset calls addstring, initwithstrings
printallexceptions calls initwithftlinkedlist, printftexceptiondescription