releaseFTLinkedListIterator – FTObjectLibrary
releaseFTLinkedListIterator Subroutine
9 statements
Source File
public subroutine releaseFTLinkedListIterator(self)
Arguments
Type Intent Optional Attributes Name
type(FTLinkedListIterator), POINTER :: self
Calls
Call graph
releaseftlinkedlistiterator calls release
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount