releaseCurrentError – FTObjectLibrary
releaseCurrentError Subroutine
9 statements
Source File
public subroutine releaseCurrentError()
Arguments
None
Calls
Called by
Call graph
releasecurrenterror calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
destructftexceptions calls releasecurrenterror
setcurrenterror calls releasecurrenterror