removeAllLinkedListObjects – FTObjectLibrary
removeAllLinkedListObjects Subroutine
22 statements
Source File
public subroutine removeAllLinkedListObjects(self)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
Calls
Called by
Call graph
removealllinkedlistobjects calls release, iscircular, makecircular
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
destructftlinkedlist calls removealllinkedlistobjects