removeObject – FTObjectLibrary
removeObject Subroutine
17 statements
Source File
public subroutine removeObject(self, obj)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
class(FTObject), POINTER :: obj
Calls
Call graph
removeobject calls removelinkedlistrecord
removelinkedlistrecord calls release, iscircular, makecircular
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount