removeLinkedListRecord – FTObjectLibrary
removeLinkedListRecord Subroutine
32 statements
Source File
public subroutine removeLinkedListRecord(self, listRecord)
Type Bound
FTLinkedList
Arguments
Type Intent Optional Attributes Name
class(FTLinkedList) :: self
class(FTLinkedListRecord), POINTER :: listRecord
Calls
Called by
Call graph
removelinkedlistrecord calls release, iscircular, makecircular
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
removecurrentrecord calls removelinkedlistrecord
removeobject calls removelinkedlistrecord