removeCurrentRecord – FTObjectLibrary
removeCurrentRecord Subroutine
9 statements
Source File
public subroutine removeCurrentRecord(self)
Type Bound
FTLinkedListIterator
Arguments
Type Intent Optional Attributes Name
class(FTLinkedListIterator) :: self
Calls
Call graph
removecurrentrecord calls removelinkedlistrecord
removelinkedlistrecord calls release, iscircular, makecircular
release calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount