replaceObjectAtIndexWithObject – FTObjectLibrary
replaceObjectAtIndexWithObject Subroutine
11 statements
Source File
public subroutine replaceObjectAtIndexWithObject(self, indx, replacement)
Replace an object at the index indx
Usage
  CLASS(FTMutableObjectArray) :: array
  INTEGER                     :: indx
  CALL array % replaceObjectAtIndexWithObject(indx)
Type Bound
FTMutableObjectArray
Arguments
Type Intent Optional Attributes Name
class(FTMutableObjectArray) :: self
integer :: indx
class(FTObject), POINTER :: replacement
Calls
Call graph
replaceobjectatindexwithobject calls releaseftobject, retainftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount