retainFTObject – FTObjectLibrary
retainFTObject Subroutine
5 statements
Source File
public subroutine retainFTObject(self)
Retain increases the reference count by one and implies ownership to the caller. ### Usage: CALL obj\ % retain()
Type Bound
FTObject
Arguments
Type Intent Optional Attributes Name
class(FTObject) :: self
Called by
Call graph
addobjecttoarray calls retainftobject
initwithobject calls retainftobject
initwithobjectandkey calls retainftobject
initwithobjectandkeys calls retainftobject
pop calls retainftobject
replaceobjectatindexwithobject calls retainftobject
setcurrenterror calls retainftobject
setinfodictionary calls retainftobject
setlinkedlist calls retainftobject
add calls initwithobject
addobjectforkey calls initwithobjectandkey, add
addobjecttomultiindextableforkeys calls initwithobjectandkeys, add
addobjecttosparsematrixforkeys calls initwithobjectandkey, add, sparsematrixcontainskeys
alllinkedlistobjects calls addobjecttoarray
allobjects calls addobjecttoarray
initftexception calls setinfodictionary
initwithftlinkedlist calls setlinkedlist
insertobjectafterrecord calls initwithobject
objectinsparsematrixforkeys calls setlinkedlist
poplastexception calls pop
push calls initwithobject
sparsematrixcontainskeys calls setlinkedlist
adddoubleprecisionvalueforkey calls addobjectforkey
addintegervalueforkey calls addobjectforkey
addlogicalvalueforkey calls addobjectforkey
addobjectsfromlist calls add
addquadvalueforkey calls addobjectforkey
addrealvalueforkey calls addobjectforkey
addstring calls addobjectforkey
addstringvalueforkey calls addobjectforkey
initassertionfailureexception calls addobjectforkey, initftexception, addvalueforkey
initfatalexception calls initftexception, addvalueforkey
initwarningexception calls initftexception, addvalueforkey
insertobjectafterobject calls add, insertobjectafterrecord
printallexceptions calls initwithftlinkedlist
throw calls push
destructftexceptions calls printallexceptions
initwithstrings calls addstring
intersectionwithset calls addstring
setfromdifference calls addstring
unionwithset calls addstring, initwithstrings