setCurrentError – FTObjectLibrary
setCurrentError Subroutine
7 statements
Source File
public subroutine setCurrentError(e)
Arguments
Type Intent Optional Attributes Name
class(FTException), POINTER :: e
Calls
Call graph
setcurrenterror calls releasecurrenterror, retainftobject
releasecurrenterror calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount