setInfoDictionary – FTObjectLibrary
setInfoDictionary Subroutine
8 statements
Source File
public subroutine setInfoDictionary(self, dict)
Sets and retains the exception infoDictionary
Type Bound
FTException
Arguments
Type Intent Optional Attributes Name
class(FTException) :: self
class(FTDictionary), POINTER :: dict
Calls
Called by
Call graph
setinfodictionary calls releasememberdictionary, retainftobject
releasememberdictionary calls releaseftobject
releaseftobject calls printftobjectdescription
printftobjectdescription calls refcount
initftexception calls setinfodictionary
initassertionfailureexception calls initftexception
initfatalexception calls initftexception
initwarningexception calls initftexception