setToStart – FTObjectLibrary
setToStart Subroutine
5 statements
Source File
public subroutine setToStart(self)
Type Bound
FTLinkedListIterator
Arguments
Type Intent Optional Attributes Name
class(FTLinkedListIterator) :: self
Called by
Call graph
initwithftlinkedlist calls settostart, setlinkedlist
printallexceptions calls settostart, initwithftlinkedlist
setlinkedlist calls settostart
sparsematrixcontainskeys calls settostart, setlinkedlist
addobjecttosparsematrixforkeys calls sparsematrixcontainskeys
destructftexceptions calls printallexceptions
objectinsparsematrixforkeys calls setlinkedlist