stringValueR – FTObjectLibrary
stringValueR Function
35 statements
Source File
public function stringValueR(self, requestedLength) result(s)
Get the string value of length requestedLength stored in the object, or convert the value in the object to a string of that length if it is of a different type. This version is deprecated in favor of the stringValueA function that uses allocated strings. This version is included only so that other code that uses this library doesn't break. It is overloaded as stringValue(requestedLength).
Type Bound
FTValue
Arguments
Type Intent Optional Attributes Name
class(FTValue) :: self
integer :: requestedLength
Return Value character(len=requestedLength)
Called by
Call graph
ftvaluedescription calls stringvalue
stringvalueforkeya calls stringvalue
stringvalueforkeyr calls stringvalue
printvaluedescription calls ftvaluedescription