strings – FTObjectLibrary
strings Function
6 statements
Source File
public function strings(self) result(s)
strings returns a pointer to an array of strings that are in the set. Deallocate this array when done with it.
Usage:
  CHARACTER(LEN=FTDICT_KWD_STRING_LENGTH) ,DIMENSION(:), POINTER :: s
  s => set % strings
  ... do something ...
  DEALLOCATE(s)
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
Return Value character(len=FTDICT_KWD_STRING_LENGTH), DIMENSION(:), POINTER
Calls
Called by
Call graph
strings calls allkeys
allkeys calls key
intersectionwithset calls strings
setfromdifference calls strings
unionwithset calls strings