stringValueForKeyR – FTObjectLibrary
stringValueForKeyR Function
16 statements
Source File
public function stringValueForKeyR(self, key, requestedLength)
Type Bound
FTValueDictionary
Arguments
Type Intent Optional Attributes Name
class(FTValueDictionary) :: self
character(len=*) :: key
integer :: requestedLength
Return Value character(len=requestedLength)
Calls
Call graph
stringvalueforkeyr calls stringvalue, objectforkey, valuefromobject
objectforkey calls b3hs_hash_key_jenkins