throw – FTObjectLibrary
throw Subroutine
11 statements
Source File
public subroutine throw(exceptionToThrow)
Throws the exception: exceptionToThrow
Arguments
Type Intent Optional Attributes Name
type(FTException), POINTER :: exceptionToThrow
Calls
Call graph
throw calls initializeftexceptions, push, severity
initializeftexceptions calls initftstack
push calls initwithobject
initftstack calls initftlinkedlist
initwithobject calls initftobject, retainftobject
initftlinkedlist calls initftobject