unionWithSet – FTObjectLibrary
unionWithSet Function
16 statements
Source File
public function unionWithSet(self, set) result(newSet)
unionWithSet returns a pointer to a new set that is the union of two sets. the new set has reference count of 1. Release when done.
Usage:
  newSet => set1 % unionWithSet(set2)
  ... do something ...
  call releaseFTStringSet(newSet)
Type Bound
FTStringSet
Arguments
Type Intent Optional Attributes Name
class(FTStringSet) :: self
class(FTStringSet) :: set
Return Value type(FTStringSet), POINTER
Calls
Call graph
unionwithset calls addstring, initwithstrings, strings
addstring calls release, addobjectforkey, containskey, initftobject
initwithstrings calls addstring, initftstringset
strings calls allkeys
release calls releaseftobject
addobjectforkey calls release, add, b3hs_hash_key_jenkins, initwithobjectandkey
allkeys calls key
containskey calls objectforkey
initftstringset calls initftobject, initwithsize
add calls initwithobject
initwithobjectandkey calls initftobject, retainftobject
initwithsize calls initftobject
objectforkey calls b3hs_hash_key_jenkins
releaseftobject calls printftobjectdescription
initwithobject calls initftobject, retainftobject
printftobjectdescription calls refcount