#!/bin/bash

# Fail fast and verbosely
set -eox pipefail

# Clean up
make clean

# Build test suite
make -j 2 FC=$FC FFLAGS="-cpp --coverage -O0" LDFLAGS="--coverage"

# Reset counters
lcov --directory . --zerocounters

# Run tests
./runSuite

# Process coverage
lcov --directory . --capture --output-file lcov.info
