cast – FTObjectLibrary
cast Interface
3 statements
Source File
public interface cast
Calls
Called by
Module Procedures
public subroutine castObjectToMatrixData(obj, cast)
Arguments
Type Intent Optional Attributes Name
class(FTObject), POINTER :: obj
class(MatrixData), POINTER :: cast
Call graph
cast calls castobjecttomatrixdata
objectinsparsematrixforkeys calls cast
sparsematrixcontainskeys calls cast
addobjecttosparsematrixforkeys calls sparsematrixcontainskeys