cast – FTObjectLibrary
cast Interface
3 statements
Source File
public interface cast
Calls
Called by
Contents
Module Procedures
castToMutableObjectArray
Module Procedures
public subroutine castToMutableObjectArray(obj, cast)
Arguments
Type Intent Optional Attributes Name
class(FTObject), POINTER :: obj
class(FTMutableObjectArray), POINTER :: cast
Call graph
cast calls casttomutableobjectarray
peeklastexception calls cast
poplastexception calls cast
printallexceptions calls cast
destructftexceptions calls printallexceptions