cast – FTObjectLibrary
cast Interface
3 statements
Source File
public interface cast
Calls
Called by
Module Procedures
public subroutine castObjectToMultiIndexMatrixData(obj, cast)
Arguments
Type Intent Optional Attributes Name
class(FTObject), POINTER :: obj
class(MultiIndexMatrixData), POINTER :: cast
Call graph
cast calls castobjecttomultiindexmatrixdata
multiindextablecontainskeys calls cast
objectinmultiindextableforkeys calls cast
addobjecttomultiindextableforkeys calls multiindextablecontainskeys