TestObjectsMain – FTObjectLibrary
TestObjectsMain Program
27 statements
Source File
Uses:
TestSuiteManagerClass
Calls
Variables
testSuite numberOfFailedTests
Variables
Type Attributes Name Initial
type(TestSuiteManager) :: testSuite
integer :: numberOfFailedTests
All Programs
TestObjectsMain
Call graph
testobjectsmain calls init, finalize, performtests, addtestsubroutinewithname