name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
  workflow_dispatch:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gfortran-10
            cmake_generator: Unix Makefiles
          - os: macos-latest
            compiler: gfortran-11
            cmake_generator: Unix Makefiles
          - os: windows-latest
            compiler: gfortran
            shell: 'msys2 {0}'
            cmake_generator: MinGW Makefiles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Add msbuild to PATH
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   uses: microsoft/setup-msbuild@v1.0.2
      - name: Verify CMake build
        run: |
          mkdir build && cd build
          cmake -G "${{ matrix.cmake_generator }}" ../
          make
        env:
          FC: ${{ matrix.compiler }}
      - name: Verify regular build
        run: |
          cd makeLibrary
          make -j 2 FC=${{ matrix.compiler }}
      - name: Build test suite
        run: |
          cd TestSuiteBuild
          make -j 2 FC=${{ matrix.compiler }}
      - name: Run tests
        run: |
          cd TestSuiteBuild
          ./runSuite
      - name: Run tests for coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y lcov
          cd TestSuiteBuild
          FC=${{ matrix.compiler }} ./createcoverage
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          files: ./TestSuiteBuild/lcov.info
          flags: unittests
          name: codecov-umbrella
      - name: Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./TestSuiteBuild/lcov.info
